server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNMT05HRW5vdWdoMTIzNDU=
  expiration: 86400000
