server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Microservice-Assignment2/config-repo

management:
  endpoints:
    web:
      exposure:
        include: "*"
